services:
  whisper:
    image: whisper-with-models
    container_name: whisper
    volumes:
      - ./media:/media
      - ./out:/out
    entrypoint: [ "whisper" ]
    command: [ "/media/monitor_answers.mp4", "--language", "Russian", "--model", "medium", "--output_dir", "/out" ]
